### ISSUE TITLE
Python 3.6 builds

### ISSUE THREAD

**Issue by mbargull** [conda-forge/setuptools_scm_git_archive-feedstock#1]
Could you lets the CI system create some Python 3.6 builds? Much appreciated!
And/or alternatively: Should this maybe become a `noarch: python` package?

**Comment by xhochy** [comment]
@mbargull Can you do a PR for `noarch: python` ? The remaining things can then be done by a bot on that PR.

**Comment by mbargull** [comment]
Will do.
Do you know upfront if `noarch: python` cause any trouble with non-`console_scripts` entry points?
`setuptools_scm_git_archive` uses:
https://github.com/Changaco/setuptools_scm_git_archive/tree/1c6421d4eae834a021223241eceb72d13a6e8375/setup.py#L7-L10
https://github.com/Changaco/setuptools_scm_git_archive/tree/1c6421d4eae834a021223241eceb72d13a6e8375/setup.py#L23-L26

**Comment by xhochy** [comment]
@mbargull no idea.

**Comment by xhochy** [comment]
Should be fixed by https://github.com/conda-forge/setuptools_scm_git_archive-feedstock/pull/2
